# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'funcion.ui'
#
# Created: Sun Mar 15 20:47:16 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from PyQt4 import QtCore
from PyQt4 import QtGui
from PyQt4.QtGui import *
from functions import Ui_DockWidget_2
try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DockWidget(QtGui.QDockWidget):
    def __init__(self,parent,target_area):
        super(Ui_DockWidget, self).__init__(parent)
        self.setupUi(self)
        self.hide()
        self.target=target_area
        self.setFloating(True)
        self.myKeyboard_2=Ui_DockWidget_2(self,self.target)
        #self.setAllowedAreas(None)
        
    def setupUi(self, DockWidget):
        DockWidget.setObjectName(_fromUtf8("DockWidget"))
        DockWidget.resize(911, 296)
        DockWidget.setStyleSheet("\n"
            " QDockWidget{\n"
" background-color:#737373;\n"
" border:none;\n"
" padding:0px; \n"
"}\n"
" QPushButton{ \n"
"position: relative;\n"
" border:none;\n"
" outline:none; \n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.664, x2:0, y2:0, stop:0.357955 rgba(89, 189, 9, 255), stop:0.801136 rgba(120, 255, 13, 255), stop:0.9375 rgba(175, 255, 111, 255), stop:1 rgba(255, 255, 255, 255));\n"
" color: white;\n"
" padding: 6px 20px; \n"
"border-radius: 2px;\n"
" font-size: 20px;\n"
" }\n"
" QPushButton:hover:!pressed{ \n"
"position: relative;\n"
" border: none; \n"
"outline:none;\n"
" background:qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0.0802727, stop:0 rgba(255, 255, 255, 255), stop:0.0397727 rgba(222, 255, 196, 255), stop:0.176136 rgba(168, 255, 99, 255), stop:0.642045 rgba(127, 200, 70, 255));\n"
" color: white; \n"
"padding: 6px 20px; \n"
"border-radius: 2px;\n"
" font-size:20px; \n"
"} \n")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.frame = QtGui.QFrame(self.dockWidgetContents)
        self.frame.setGeometry(QtCore.QRect(0, 10, 331, 240))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pushButton_13 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_13.sizePolicy().hasHeightForWidth())
        self.pushButton_13.setSizePolicy(sizePolicy)
        self.pushButton_13.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setPointSize(20)
        font.setBold(False)
        self.pushButton_13.setFont(font)
        self.gridLayout_3.addWidget(self.pushButton_13, 5, 4, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_3.addWidget(self.pushButton_6, 2, 0, 1, 1)
        self.pushButton_17 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_17.sizePolicy().hasHeightForWidth())
        font.setPointSize(18)
        font.setBold(False)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setSizePolicy(sizePolicy)
        self.pushButton_17.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.gridLayout_3.addWidget(self.pushButton_17, 2, 3, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_3.addWidget(self.pushButton_4, 6, 4, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Century Schoolbook L"))
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_3.addWidget(self.pushButton_7, 2, 1, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_12.sizePolicy().hasHeightForWidth())
        self.pushButton_12.setSizePolicy(sizePolicy)
        self.pushButton_12.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_3.addWidget(self.pushButton_12, 2, 4, 1, 1)
        self.pushButton_10 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_10.sizePolicy().hasHeightForWidth())
        self.pushButton_10.setSizePolicy(sizePolicy)
        self.pushButton_10.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_3.addWidget(self.pushButton_10, 4, 1, 1, 1)
        self.pushButton_14 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_14.sizePolicy().hasHeightForWidth())
        self.pushButton_14.setSizePolicy(sizePolicy)
        self.pushButton_14.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TlwgTypewriter"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.gridLayout_3.addWidget(self.pushButton_14, 4, 3, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 6, 3, 1, 1)
        self.pushButton_16 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_16.sizePolicy().hasHeightForWidth())
        self.pushButton_16.setSizePolicy(sizePolicy)
        self.pushButton_16.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Serif"))
        font.setPointSize(12)
        font.setItalic(True)
        self.pushButton_16.setFont(font)
        self.pushButton_12.setFont(font)
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.gridLayout_3.addWidget(self.pushButton_16, 5, 0, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        font = QtGui.QFont()
        font.setWeight(50)
        font.setPointSize(20)
        font.setBold(False)
        self.pushButton_2.setFont(font)
        self.gridLayout_3.addWidget(self.pushButton_2, 5, 3, 1, 1)
        self.pushButton_11 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_11.sizePolicy().hasHeightForWidth())
        self.pushButton_11.setSizePolicy(sizePolicy)
        self.pushButton_11.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TlwgTypewriter"))
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_3.addWidget(self.pushButton_11, 4, 4, 1, 1)
        self.pushButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 4, 0, 1, 1)
        self.pushButton_15 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_15.sizePolicy().hasHeightForWidth())
        self.pushButton_15.setSizePolicy(sizePolicy)
        self.pushButton_15.setMinimumSize(QtCore.QSize(100, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSerif"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.gridLayout_3.addWidget(self.pushButton_15, 6, 0, 1, 3)
        self.pushButton_28 = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_28.sizePolicy().hasHeightForWidth())
        self.pushButton_28.setSizePolicy(sizePolicy)
        self.pushButton_28.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setObjectName(_fromUtf8("pushButton_28"))
        self.gridLayout_3.addWidget(self.pushButton_28, 5, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.frame_2 = QtGui.QFrame(self.dockWidgetContents)
        self.frame_2.setGeometry(QtCore.QRect(340, 10, 331, 240))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setVerticalSpacing(6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.pushButton_24 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setObjectName(_fromUtf8("pushButton_24"))
        self.gridLayout_4.addWidget(self.pushButton_24, 4, 2, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_9.sizePolicy().hasHeightForWidth())
        self.pushButton_9.setSizePolicy(sizePolicy)
        self.pushButton_9.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_4.addWidget(self.pushButton_9, 5, 1, 1, 1)
        self.pushButton_18 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TlwgTypewriter"))
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.gridLayout_4.addWidget(self.pushButton_18, 5, 3, 1, 1)
        self.pushButton_19 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_19.sizePolicy().hasHeightForWidth())
        self.pushButton_19.setSizePolicy(sizePolicy)
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.gridLayout_4.addWidget(self.pushButton_19, 2, 0, 1, 1)
        self.pushButton_20 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_20.sizePolicy().hasHeightForWidth())
        self.pushButton_20.setSizePolicy(sizePolicy)
        self.pushButton_20.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.gridLayout_4.addWidget(self.pushButton_20, 2, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TlwgTypewriter"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_4.addWidget(self.pushButton_5, 6, 3, 1, 1)
        self.pushButton_21 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_21.sizePolicy().hasHeightForWidth())
        self.pushButton_21.setSizePolicy(sizePolicy)
        self.pushButton_21.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.gridLayout_4.addWidget(self.pushButton_21, 2, 1, 1, 1)
        self.pushButton_22 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.gridLayout_4.addWidget(self.pushButton_22, 2, 3, 1, 1)
        self.pushButton_23 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_23.sizePolicy().hasHeightForWidth())
        self.pushButton_23.setSizePolicy(sizePolicy)
        self.pushButton_23.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        self.gridLayout_4.addWidget(self.pushButton_23, 4, 1, 1, 1)
        self.pushButton_31 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_31.sizePolicy().hasHeightForWidth())
        self.pushButton_31.setSizePolicy(sizePolicy)
        self.pushButton_31.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_31.setObjectName(_fromUtf8("pushButton_31"))
        self.gridLayout_4.addWidget(self.pushButton_31, 4, 3, 1, 1)
        self.pushButton_25 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TlwgTypewriter"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setObjectName(_fromUtf8("pushButton_25"))
        self.gridLayout_4.addWidget(self.pushButton_25, 6, 2, 1, 1)
        self.pushButton_26 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setObjectName(_fromUtf8("pushButton_26"))
        self.gridLayout_4.addWidget(self.pushButton_26, 5, 0, 1, 1)
        self.pushButton_27 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_27.sizePolicy().hasHeightForWidth())
        self.pushButton_27.setSizePolicy(sizePolicy)
        self.pushButton_27.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setObjectName(_fromUtf8("pushButton_27"))
        self.gridLayout_4.addWidget(self.pushButton_27, 5, 2, 1, 1)
        self.pushButton_29 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_29.sizePolicy().hasHeightForWidth())
        self.pushButton_29.setSizePolicy(sizePolicy)
        self.pushButton_29.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setObjectName(_fromUtf8("pushButton_29"))
        self.gridLayout_4.addWidget(self.pushButton_29, 4, 0, 1, 1)
        self.pushButton_30 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_30.sizePolicy().hasHeightForWidth())
        self.pushButton_30.setSizePolicy(sizePolicy)
        self.pushButton_30.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setObjectName(_fromUtf8("pushButton_30"))
        self.gridLayout_4.addWidget(self.pushButton_30, 6, 0, 1, 1)
        self.pushButton_32 = QtGui.QPushButton(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_32.sizePolicy().hasHeightForWidth())
        self.pushButton_32.setSizePolicy(sizePolicy)
        self.pushButton_32.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("TlwgTypewriter"))
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setObjectName(_fromUtf8("pushButton_32"))
        self.gridLayout_4.addWidget(self.pushButton_32, 6, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.frame_3 = QtGui.QFrame(self.dockWidgetContents)
        self.frame_3.setGeometry(QtCore.QRect(680, 10, 198, 241))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.pushButton_8 = QtGui.QPushButton(self.frame_3)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.verticalLayout_3.addWidget(self.pushButton_8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_34 = QtGui.QPushButton(self.frame_3)
        self.pushButton_34.setMinimumSize(QtCore.QSize(20, 40))
        self.pushButton_34.setObjectName(_fromUtf8("pushButton_34"))
        self.horizontalLayout.addWidget(self.pushButton_34)
        self.pushButton_33 = QtGui.QPushButton(self.frame_3)
        self.pushButton_33.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_33.setObjectName(_fromUtf8("pushButton_33"))
        self.horizontalLayout.addWidget(self.pushButton_33)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.pushButton_35 = QtGui.QPushButton(self.frame_3)
        self.pushButton_35.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_35.setObjectName(_fromUtf8("pushButton_35"))
        self.verticalLayout_3.addWidget(self.pushButton_35)
        font = QtGui.QFont()
        #font.setWeight(50)
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(True)
        self.pushButton_3.setFont(font)
        self.pushButton_33.setFont(font)
        self.pushButton_34.setFont(font)
        self.pushButton_22.setFont(font)
        self.pushButton_31.setFont(font)
        self.pushButton_35.setFont(font)
        font.setPointSize(16)
        font.setBold(False)
        self.pushButton_4.setFont(font)
        self.pushButton_8.clicked.connect(lambda:self.show_1(self.myKeyboard_2))
        DockWidget.setWidget(self.dockWidgetContents)
        self.pushButton_13.clicked.connect(self.function_11)
        self.pushButton_6.clicked.connect(lambda:self.function_14("x"))
        self.pushButton_17.clicked.connect(self.function_2)
        self.pushButton_4.clicked.connect(self.function_13)
        self.pushButton_7.clicked.connect(lambda:self.function_14("y"))
        self.pushButton_12.clicked.connect(self.function_3)
        self.pushButton_10.clicked.connect(lambda:self.function_14(")"))
        self.pushButton_14.clicked.connect(lambda:self.function_14("<"))
        self.pushButton_3.clicked.connect(self.function_12)
        self.pushButton_16.clicked.connect(self.function_8)
        self.pushButton_2.clicked.connect(self.function_10)
        self.pushButton_11.clicked.connect(lambda:self.function_14(">"))
        self.pushButton.clicked.connect(lambda:self.function_14("("))
        self.pushButton_15.clicked.connect(lambda:self.function_14(" "))
        self.pushButton_28.clicked.connect(lambda:self.function_14(","))
        self.pushButton_24.clicked.connect(lambda:self.function_14("6"))
        self.pushButton_9.clicked.connect(lambda:self.function_14("2"))
        self.pushButton_18.clicked.connect(lambda:self.function_14("-"))
        self.pushButton_19.clicked.connect(lambda:self.function_14("7"))
        self.pushButton_20.clicked.connect(lambda:self.function_14("9"))
        self.pushButton_5.clicked.connect(lambda:self.function_14("+"))
        self.pushButton_21.clicked.connect(lambda:self.function_14("8"))
        self.pushButton_22.clicked.connect(self.function_15)
        self.pushButton_23.clicked.connect(lambda:self.function_14("5"))
        self.pushButton_31.clicked.connect(self.function_16)
        self.pushButton_25.clicked.connect(lambda:self.function_14("="))
        self.pushButton_26.clicked.connect(lambda:self.function_14("1"))
        self.pushButton_27.clicked.connect(lambda:self.function_14("3"))
        self.pushButton_29.clicked.connect(lambda:self.function_14("4"))
        self.pushButton_30.clicked.connect(lambda:self.function_14("0"))
        self.pushButton_32.clicked.connect(lambda:self.function_14("."))
        self.pushButton_34.clicked.connect(self.function_17)
        self.pushButton_33.clicked.connect(self.function_18)
        self.pushButton_35.clicked.connect(self.function_19)

        self.retranslateUi(DockWidget)
        QtCore.QMetaObject.connectSlotsByName(DockWidget)

    def show_1(self,at):
        if self.myKeyboard_2.isVisible()==False:
            self.myKeyboard_2.move(1920-293,1080-411-296)
            self.myKeyboard_2.setTarget(self.target)
            self.myKeyboard_2.show()
        else:
            self.myKeyboard_2.hide()

    def function(self):
        self.target.insert("x")
    def function_1(self):
        self.target.insert("y")
    def function_2(self):
        self.target.insert(u'\u00B2')
    # very very hard !!!
    def function_3(self):
        self.target.insert(u'\u1D47')
    def function_4(self):
        self.target.insert("(")
    def function_5(self):
        self.target.insert(")")
    def function_6(self):
        self.target.insert("<")
    def function_7(self):
        self.target.insert(">")
    def function_8(self):
        self.target.insert("||")
        self.target.setCursorPosition(self.target.cursorPosition()-1)
    def function_9(self):
        self.target.insert(",")
    def function_10(self):
        self.target.insert(u'\u2264')#<=
    def function_11(self):
        self.target.insert(u'\u2265')#>=
    def function_12(self):
        self.target.insert(u'\u221A')#sqrt
    def function_13(self):
        self.target.insert(u'\u03C0')#pi
    def function_14(self,str_num):
        self.target.insert(str_num)    
    def function_15(self):
        self.target.insert(u'\u00F7')#divide
    def function_16(self):
        self.target.insert(u'\u00D7')#multiply
    def function_17(self):
        self.target.setCursorPosition(self.target.cursorPosition()-1)
    def function_18(self):
        self.target.setCursorPosition(self.target.cursorPosition()+1)
    def function_19(self):
        self.target.backspace()
    def setTarget(self,target_area):
        self.target=target_area

    def retranslateUi(self, DockWidget):
        #DockWidget.setWindowTitle(_translate("DockWidget", "Keyboard", None))
        self.pushButton_13.setText(_translate("DockWidget", u'\u2265', None))#Greater than equal to
        self.pushButton_6.setText(_translate("DockWidget", "x", None))
        self.pushButton_17.setText(_translate("DockWidget", u'x\u00B2', None))#Square
        self.pushButton_4.setText(_translate("DockWidget", u'\u03C0', None))# pi
        self.pushButton_7.setText(_translate("DockWidget", "y", None))
        self.pushButton_12.setText(_translate("DockWidget", u'a\u1D47', None))# a^b
        self.pushButton_10.setText(_translate("DockWidget", ")", None))
        self.pushButton_14.setText(_translate("DockWidget", "<", None))
        self.pushButton_3.setText(_translate("DockWidget", u'\u221A', None))# root
        self.pushButton_16.setText(_translate("DockWidget", "|a|", None))
        self.pushButton_2.setText(_translate("DockWidget", u'\u2264', None))# Less Than Equal to
        self.pushButton_11.setText(_translate("DockWidget", ">", None))
        self.pushButton.setText(_translate("DockWidget", "(", None))
        self.pushButton_15.setText(_translate("DockWidget", "               SPACE               ", None))
        self.pushButton_28.setText(_translate("DockWidget", ",", None))
        self.pushButton_24.setText(_translate("DockWidget", "6", None))
        self.pushButton_9.setText(_translate("DockWidget", "2", None))
        self.pushButton_18.setText(_translate("DockWidget", "-", None))
        self.pushButton_19.setText(_translate("DockWidget", "7", None))
        self.pushButton_20.setText(_translate("DockWidget", "9", None))
        self.pushButton_5.setText(_translate("DockWidget", "+", None))
        self.pushButton_21.setText(_translate("DockWidget", "8", None))
        self.pushButton_22.setText(_translate("DockWidget", u'\u00F7', None))#Divide
        self.pushButton_23.setText(_translate("DockWidget", "5", None))
        self.pushButton_31.setText(_translate("DockWidget", u'\u00D7', None))#multiply
        self.pushButton_25.setText(_translate("DockWidget", "=", None))
        self.pushButton_26.setText(_translate("DockWidget", "1", None))
        self.pushButton_27.setText(_translate("DockWidget", "3", None))
        self.pushButton_29.setText(_translate("DockWidget", "4", None))
        self.pushButton_30.setText(_translate("DockWidget", "0", None))
        self.pushButton_32.setText(_translate("DockWidget", ".", None))
        self.pushButton_8.setText(_translate("DockWidget", "functions", None))
        self.pushButton_34.setText(_translate("DockWidget", u'\u2190', None))#LeftArrow
        self.pushButton_33.setText(_translate("DockWidget", u'\u2192', None))#Right Arrow
        self.pushButton_35.setText(_translate("DockWidget", u'\u232B', None))#BackSpace

if __name__ == "__main__":
    import sys
    a = QtGui.QApplication(sys.argv)
    w=Ui_DockWidget(None,None)
    w.show()
    sys.exit(a.exec_())